[project]
name = "pygent"
version = "0.1.0"
description = "AI agent experimentation"
dependencies = ["requests"]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
